env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
plugins:
  - '@typescript-eslint'
  - react-hooks
parser: '@typescript-eslint/parser'
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
